### ISSUE TITLE
some bugs here , I tried your code ,and .....

### ISSUE THREAD

**Issue by keacifer** [shzygmyx/Matrix-Capsules-pytorch#6]

**Comment by keacifer** [comment]
activating cuda
Epoch 0
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    loss = model.loss(out_labels, labels, m)
  File "train.py", line 43, in loss
    a_t = torch.cat([x[i][target[i]] for i in range(b)]) #b
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

**Comment by bobchenlut** [comment]
I met this bug too.

**Comment by ChunningDu** [comment]
Have you solved it?

**Comment by RahulSChand** [comment]
Change the loss function in train.py to below.

```
def loss(self, x, target, m): #x:b,10 target:b        
        target = target*x
        zero_tensor = torch.tensor(0.0).cuda()
        loss = torch.max(zero_tensor,m-(target-x))**2
        loss = torch.mean(loss)
        return loss
```

And rather than passing **labels** as the 2nd argument to model.loss() pass **torch.eye(10).index_select(dim=0,index=labels)** this. That is on line _96_ the code is 
`loss = model.loss(out_labels, labels, m)`  change  that to 
`loss = model.loss(out_labels, torch.eye(10).index_select(dim=0,index=labels), m)`

This will work if your use_cuda flag is False. If it is set to True, do the following:
After line _92_ define a new variable
`labels_zero = torch.eye(10).index_select(dim=0,index=labels).cuda()`
and then on line _96_
`loss = model.loss(out_labels, labels, m)`  change this to
`loss = model.loss(out_labels, labels_zero, m)`

**Comment by RahulSChand** [comment]
Also considering you got an issue at line 43, you may additionally get an error at line _102_  `acc = pred.eq(labels).cpu().sum().data[0]` in that case change it to  `acc = pred.eq(labels).cpu().sum().item()`

**Comment by FreshFood** [comment]
Pytorch version problem
a_t = torch.cat([x[i][target[i]].unsqueeze(0) for i in range(b)])
